AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

require:
  - rubocop-rake
  - rubocop-minitest

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
